version: "3.7"
services:
  app:
    container_name: bom-proj-nextjs
    image: 'bomtawep/bom-nextjs-webapp:latest'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    restart: on-failure
  web:
    container_name: 'bom-nginx'
    image: 'bomtawep/bom-nginx:latest'
    volumes:
      - ./nginx/nginx.production.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    restart: on-failure
    depends_on:
      - 'app'