version: "3.7"
networks:
  ingress:
    driver: bridge
services:
  app:
    container_name: bom-proj-nextjs
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    restart: on-failure
    networks:
      - ingress
  web:
    container_name: 'bom-nginx'
    build:
      context: .
      args:
        APP_ENV: development
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.development.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - 'app'
    restart: on-failure
    networks:
      - ingress